#!/usr/bin/env python3
"""
Adds the foreign keys of hocon/config/relations.conf to exported/exportedConfig.json.

The exported config is generated by SDLB's ConfigJsonExporter and downloaded as a whole, so a
fixture refresh would drop anything edited into it by hand. update-fixtures.sh runs this script
after the download instead, and it is idempotent, so running it again changes nothing.

Keep the keys here in sync with hocon/config/relations.conf - the two Playwright projects read
the same configuration through the two different config sources and must see the same relations.
"""
import json
import sys
from pathlib import Path

FOREIGN_KEYS = {
    "int-departures": [
        {"name": "fk_departure_airport", "dataObjectId": "int-airports",
         "columns": {"estdepartureairport": "ident"}},
        {"name": "fk_arrival_airport", "dataObjectId": "int-airports",
         "columns": {"estarrivalairport": "ident"}},
        # the pre 3.x form, naming a table instead of a data object - ignored by the UI
        {"name": "fk_legacy", "db": "reference", "table": "airlines",
         "columns": {"legacy_column": "callsign"}},
    ],
    "btl-departures-arrivals-airports": [
        {"name": "fk_arrival_airport", "dataObjectId": "int-airports",
         "columns": {"estarrivalairport": "ident"}},
        # points at a data object this configuration does not describe
        {"name": "fk_airline", "dataObjectId": "int-airlines",
         "columns": {"callsign": "callsign"}},
    ],
}


def main(path: Path) -> int:
    config = json.loads(path.read_text())
    data_objects = config.get("dataObjects", {})
    for data_object_id, foreign_keys in FOREIGN_KEYS.items():
        data_object = data_objects.get(data_object_id)
        if data_object is None:
            print(f"{path}: no data object '{data_object_id}' - fixtures changed?", file=sys.stderr)
            return 1
        table = data_object.setdefault("table", {})
        table["foreignKeys"] = foreign_keys
    path.write_text(json.dumps(config, separators=(",", ":"), sort_keys=True))
    print(f"patched foreign keys into {path}")
    return 0


if __name__ == "__main__":
    here = Path(__file__).resolve().parent
    target = Path(sys.argv[1]) if len(sys.argv) > 1 else here / "exported" / "exportedConfig.json"
    sys.exit(main(target))
