#!/usr/bin/env bash
#
# Downloads the E2E test fixtures from the smart-data-lake/getting-started repository.
#
# The fixtures are committed to git so that tests are deterministic and run offline.
# Only run this script to intentionally refresh them, then review + commit the diff.
#
# Sources (mirrors what getting-started/.github/workflows/ui-build.yml deploys):
#   - config:           the part-3-solution HOCON files (incremental mode) + global.conf
#   - envConfig/dev.conf
#   - exportedConfig.json: taken from the deployed GitHub Pages site, since it is
#                          generated by SDLB's ConfigJsonExporter and not committed
#   - state:            a pinned subset of the runs in viz/state
#   - schema/description: the artifacts of the schema exporter
#
set -euo pipefail

# Pin to a commit so fixtures don't silently change. Update deliberately.
SHA="${1:-927f04641341712cf3cf00507f883e2374278f01}"

RAW="https://raw.githubusercontent.com/smart-data-lake/getting-started/$SHA"
PAGES="https://smart-data-lake.github.io/getting-started"
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Runs kept as fixtures. 24.1 failed and was retried as 24.2 -- keep both, the
# multi-attempt case is easy to break. The rest are recent successful runs.
RUNS=(24.1 24.2 73.1 74.1 75.1)

echo "Fetching getting-started fixtures at $SHA"

# --- HOCON config (branch b) of fetchAPI_local_statefiles.getConfig) ------------
mkdir -p "$DIR/hocon/config" "$DIR/hocon/envConfig"
curl -sfL "$RAW/config/global.conf"                  -o "$DIR/hocon/config/global.conf"
curl -sfL "$RAW/config/airports.conf.part-3-solution"   -o "$DIR/hocon/config/airports.conf"
curl -sfL "$RAW/config/departures.conf.part-3-solution" -o "$DIR/hocon/config/departures.conf"
curl -sfL "$RAW/config/btl.conf.part-3-solution"        -o "$DIR/hocon/config/btl.conf"
curl -sfL "$RAW/envConfig/dev.conf"                  -o "$DIR/hocon/envConfig/dev.conf"

# index file listing the config files, used when the web server cannot list directories
( cd "$DIR/hocon/config" && ls *.conf > index )

# --- exported config (branch a), what the deployed getting-started viz uses ----
mkdir -p "$DIR/exported"
curl -sfL "$PAGES/exportedConfig.json" -o "$DIR/exported/exportedConfig.json"

# --- state files --------------------------------------------------------------
mkdir -p "$DIR/shared/state/succeeded"
for run in "${RUNS[@]}"; do
  curl -sfL "$RAW/viz/state/succeeded/getting-started.$run.json" \
       -o "$DIR/shared/state/succeeded/getting-started.$run.json"
done

# keep only the fixture runs in the index (JSON-Lines, one run per line)
curl -sfL "$RAW/viz/state/index.json" \
  | python3 -c "
import json, sys
keep = {tuple(r.split('.')) for r in '${RUNS[*]}'.split()}
for line in sys.stdin:
    if not line.strip(): continue
    run = json.loads(line)
    if (str(run['runId']), str(run['attemptId'])) in keep:
        print(json.dumps(run))
" > "$DIR/shared/state/index.json"

# Run 24 was written by an older SDLB that emitted local time without a zone, while
# newer runs end in Z. Mark them as UTC (they ran on a GitHub runner) so every fixture
# timestamp denotes the same instant wherever the tests run.
python3 "$DIR/normalize-timestamps.py" "$DIR/shared/state/index.json" "$DIR/shared/state/succeeded/"*.json

# --- schema / statistics / descriptions ---------------------------------------
mkdir -p "$DIR/shared/schema" "$DIR/shared/description/dataObjects"
for f in $(curl -sfL "https://api.github.com/repos/smart-data-lake/getting-started/contents/viz/schema?ref=$SHA" \
           | python3 -c "import sys,json;[print(x['name']) for x in json.load(sys.stdin) if x['name'].startswith(('btl-distances','int-airports'))]"); do
  curl -sfL "$RAW/viz/schema/$f" -o "$DIR/shared/schema/$f"
done
curl -sfL "$RAW/viz/description/dataObjects/btl-distances.md" -o "$DIR/shared/description/dataObjects/btl-distances.md"
curl -sfL "$RAW/viz/description/dataObjects/int-airports.md" -o "$DIR/shared/description/dataObjects/int-airports.md"

echo "Done. Fixture runs: ${RUNS[*]}"
