name: Build

on: 
  push:
    branches:
      - 'master'
      - 'develop'

jobs:
  build-and-create-release:

    runs-on: ubuntu-latest

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@main

    - run: yarn install
    - run: yarn build
      env:
        CI: '' # disable CI mode as it makes build fail on warnings

    - run: echo ARTIFACT_NAME=sdl-visualizer-${{ steps.package-version.outputs.current-version}}${{ github.ref_name != 'master' && format('-{0}', github.ref_name) || '' }} >> $GITHUB_ENV

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: |
          build/**/*.js
          build/**/*.css
          build/index.html
          build/manifest.json
          build/sdl_logo192.png
          build/lighttpd.conf
          build/README.md

    - name: 'If build on master branch, download artifact'
      if: ${{ github.ref_name == 'master' }}
      uses: actions/download-artifact@v3
      with:
        path: artifact
        name: ${{ env.ARTIFACT_NAME }}

    - name: 'If build on master branch, zip release asset'
      if: ${{ github.ref_name == 'master' }}
      uses: thedoctor0/zip-release@main
      with:
        type: zip
        directory: artifact
        filename: ${{ env.ARTIFACT_NAME }}.zip
        
    - run: ls -l
    - run: ls -l artifact

    - name: 'If build on master branch, create release'
      if: ${{ github.ref_name == 'master' }}
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        title: Release-${{ steps.package-version.outputs.current-version}}
        automatic_release_tag: ${{ steps.package-version.outputs.current-version}}
        draft: true
        files: artifact/${{ env.ARTIFACT_NAME }}.zip
